Pabellón
cetav-ddw/proxy pull request #11
Opened 2019-10-02 17:44 UTC by glorianaa80

2019-10-02 17:59 UTC, NycollSM reviewed
Comentarios de code review

2019-10-02 17:59 UTC, NycollSM commented on src/scss/sections/pabellon/pabellon.scss
> +
Anidar media queries a selectores y ponerlos antes de los estilos default

2019-10-03 03:10 UTC, jleiva requested changes

2019-10-03 03:10 UTC, jleiva commented on public/index.html
> +          <a href="./index.html" class="nav-list__link">Home</a>
Si el sitio esta en español, deberia de ser Inicio, o algo asi

2019-10-03 03:10 UTC, jleiva commented on public/pabellon.html
> +  <section class="desc-pabellón">
no tildes ni caracteres especiales en los nombres de clases, id, ni ningun atributo, aplica para toda esta seccion

2019-10-03 03:10 UTC, jleiva commented on public/pabellon.html
> +      <p class="pabellón__text pabellón__text--bold">¿QUE ES LA HIPERREALIDA?</p>
esto es un titulo?

2019-10-03 03:10 UTC, jleiva commented on public/pabellon.html
> +      <p class="req__item-text"> - Las obras seran reguistradas por la organización.</p>
si esto es una lista, usar la etiqueta correcta

2019-10-03 03:10 UTC, jleiva commented on src/scss/sections/pabellon/_pabellon.scss
> +  color: #fff;
hay una variable para blanco, $white

Mismo comentario que en el html, no tildes ni caracteres especiales para las clases

2019-10-03 03:10 UTC, jleiva commented on src/scss/sections/pabellon/_pabellon.scss
> +.req{
espacio entre el selector y el {, y hay una linea en blanco de mas

2019-10-03 03:10 UTC, jleiva commented on src/scss/sections/pabellon/_pabellon.scss
> +  padding: 27% 0 10% 0;
con base en que estan calculando los % de margin y padding?

2019-10-03 03:10 UTC, jleiva commented on src/scss/sections/pabellon/_pabellon.scss
> +    font-size: 30px;
mismo font-size que en linea 76

2019-10-03 03:10 UTC, jleiva commented on src/scss/sections/pabellon/_pabellon.scss
> +    padding: 8% 3% 0 0;
con respecto a linea 90, solo el valor de top esta cambiando, no hace falta sobreescribir todos los valores

2019-10-03 03:10 UTC, jleiva commented on src/scss/sections/proxy/_proxy.scss
> +  background: transparent url(/img/proxy.svg) no-repeat;
doble comillas para el path de la imagen

2019-10-03 03:19 UTC, jleiva requested changes

2019-10-03 03:19 UTC, jleiva commented on public/pabellon.html
> +  <meta http-equiv="X-UA-Compatible" content="ie=edge">
falta el import de google font

2019-10-03 19:16 UTC, jleiva requested changes

2019-10-03 19:16 UTC, jleiva commented on public/pabellon.html
> +        <li class="req__item">- Las obras seran reguistradas por la organización.</li>
porque el guion, es una  lista, usa CSS para usar el estilo de lista que necesitas

2019-10-03 19:16 UTC, jleiva commented on public/pabellon.html
> +    <img class="pabellon__img" src="./img/pabellon.png" alt="Pabellón">
si Pabellon es un titulo, esto deberia de ser un heading, con el texto y usar reemplazo del texto con la imagen como background image

2019-10-03 19:16 UTC, jleiva commented on public/pabellon.html
> +          <a href="#" class="nav-list__link">Pabellon</a>
Pabellon va o no va tildado?

2019-10-04 21:41 UTC, merged