Footer
cetav-ddw/proxy pull request #2
Opened 2019-09-16 22:19 UTC by glorianaa80

2019-09-18 03:45 UTC, jleiva requested changes

2019-09-18 03:45 UTC, jleiva commented on src/scss/sections/footer.scss
> +  @media (max-width: 414px) {
usemos min-width para todos los media queries

2019-09-18 03:45 UTC, jleiva commented on public/index.html
> -  <script src="main.js"></script>
el script tag lo incluye solo webpack?

2019-09-18 03:45 UTC, jleiva commented on public/index.html
> +      <a class="media__icon--link" href="https://www.instagram.com/proxy_hiperreal/?hl=es-la" target="_blank"><img class="media__icon media__icon--pdl" src="./img/insta.svg" alt=""></a>
si la imagen no tiene alt, entonces el link deberia de tener un texto

2019-09-18 15:20 UTC, glorianaa80 commented on src/scss/sections/footer.scss
> +  @media (max-width: 414px) {
yo lo hice com min-width al inicio pero a la hora de resize los cambios que estaban en el media no se hacen

2019-09-18 15:23 UTC, glorianaa80 commented on public/index.html
> +      <a class="media__icon--link" href="https://www.instagram.com/proxy_hiperreal/?hl=es-la" target="_blank"><img class="media__icon media__icon--pdl" src="./img/insta.svg" alt=""></a>
ya le puse el alt a la imagen es que se me olvido

2019-09-19 15:38 UTC, jleiva commented on src/scss/sections/footer.scss
> +  @media (max-width: 414px) {
eso esta raro, si queres lo podemos ver, pero la idea es usar min-width

2019-09-19 15:42 UTC, glorianaa80 commented on src/scss/sections/footer.scss
> +  @media (max-width: 414px) {
si porfa lo podemos ver porque no me funciona con min-width

2019-09-19 15:44 UTC, glorianaa80 commented on src/scss/sections/footer.scss
> +  @media (max-width: 414px) {
puede ser deba a que estamos empezando el diseño desde desktop a mobile o eso no tiene nada que ver??

2019-09-19 15:56 UTC, jleiva requested changes

2019-09-19 15:56 UTC, jleiva commented on public/index.html
> +  <script src="main.json"></script>
ojo aca, dedazo

2019-09-19 15:56 UTC, jleiva commented on src/scss/sections/_footer.scss
> +.allies__imgs {
La idea de los partials es poder componentizar. Lo idea es tener un partial por componente, no un solo partial grandisimo, cada cosa del footer que sea independiente se puede mover a un partial, y el partial _footer solo deberia tener las reglas que le aplican a footer, ejemplo, colores, espaciado, etc

Ya las variables estan disponibles, hay que usarlas en estos archivos.

2019-09-19 15:56 UTC, jleiva commented on public/index.html
> +          alt="Logo de Telerad Telecomunicaciones Radiodigitales">
no hace falta incluir la palabra logo en el alt

2019-09-19 15:56 UTC, jleiva commented on public/index.html
> +      <a class="media__icon--link" href="https://www.instagram.com/proxy_hiperreal/?hl=es-la" target="_blank"><img class="media__icon media__icon--pdl" src="./img/insta.svg" alt="Icono de la red soci
No podes usar un modificados sin tener un elemento, en este caso, para que no necesitas modificador para nada. Hay varios lugares parecidos, que usas sintaxis de modificador, pero no hay elemento a modificar

No hace falta incluir la palabra icono de.. en el alt, recorda que la idea de usar alt en imagenes es darle informacion relavante al usuario no vidente; puede ser algo como Perfil de Proxy en Facebook, o algo asi.

Quitales el target blank

2019-09-19 15:56 UTC, jleiva commented on src/scss/sections/_footer.scss
> +.allies__item--size1 {
estos modificadores no estan bien, no comunican nada, no son reusables. Si tienen problemas con los tamaños de los logos, una opcion es editarlos o ajustarlo para que queden de un tamaño parecido

2019-09-19 15:56 UTC, jleiva commented on public/index.html
> +    <p class="title-footer">
si esto es un titulo, porque no usas la etiqueta correcta?

2019-09-19 15:56 UTC, jleiva commented on src/scss/sections/_footer.scss
> +  @media (max-width: 768px) {
usemos min-width

2019-09-19 16:16 UTC, glorianaa80 commented on src/scss/sections/_footer.scss
> +  @media (max-width: 768px) {
el min me da problemas

2019-09-19 22:56 UTC, jleiva requested changes

2019-09-19 22:56 UTC, jleiva commented on src/scss/style.scss
> +@import './partials/general';
este paso de general esta de mas, se puede importar los componentes directamente

2019-09-19 22:56 UTC, jleiva commented on src/scss/partials/_general.scss
> +@import "./allies";
todos estos partials deberian de estar en un folder que se llame components, porque eso es lo que son, e importarlos directo en styles.scss

2019-09-19 22:56 UTC, jleiva commented on public/index.html
> +      <a class="media__icon--link" href="https://www.instagram.com/proxy_hiperreal/?hl=es-la"><img class="media__icon media__icon--pdl" src="./img/insta.svg" alt="Instagram de Proxy"></a>
no aplicaste el feedback de los modificadores

2019-09-19 22:56 UTC, jleiva commented on src/scss/partials/_allies.scss
> +  @media (min-width: 414px) {
antes de los media query debe ir una linea nueva

2019-09-19 22:56 UTC, jleiva commented on src/scss/partials/_allies.scss
> +  @media (min-width: 414px) {
este media query esta repetido

2019-09-19 22:56 UTC, jleiva commented on src/scss/sections/_footer.scss
> +footer {
la imagen se tiene que repetir?

2019-09-19 22:56 UTC, jleiva commented on src/scss/sections/_footer.scss
> +    font-size: 1.5rem;
el font size es el mismo entre breakpoints

2019-09-20 00:11 UTC, glorianaa80 commented on src/scss/sections/_footer.scss
> +footer {
no entendí eso?
a que se refiere con lo de la imagen??

2019-09-20 17:13 UTC, merged