Obras
cetav-ddw/proxy pull request #7
Opened 2019-09-23 16:03 UTC by JgeovanniAm

2019-09-24 18:58 UTC, NycollSM reviewed
Ya se hizo, code review

2019-09-24 19:57 UTC, glorianaa80 commented on src/scss/layout/_grid.scss
> +	height: auto;
A cuanto está espaciando??

2019-09-24 19:58 UTC, glorianaa80 commented on src/scss/sections/header/_date.scss
> +  display: flex;
orden alfabetico

2019-09-24 20:03 UTC, glorianaa80 commented on src/scss/sections/modalities/_social.scss
> +  grid-template-areas: "insta face"
orden alfabético

2019-09-24 20:04 UTC, glorianaa80 commented on src/scss/sections/modalities/_type.scss
> +  flex-direction: column;
orden alfabético

2019-09-24 20:08 UTC, glorianaa80 commented on src/scss/sections/works/_works.scss
> +	}
se le colo un }

2019-09-24 20:08 UTC, glorianaa80 commented on src/scss/sections/works/_works.scss
> +	}
se le colo un }

2019-09-24 20:08 UTC, glorianaa80 commented on src/scss/sections/works/_works.scss
> +  }
se le colo un }

2019-09-24 20:09 UTC, glorianaa80 commented on src/scss/sections/works/_works.scss
> +	}
otro }

2019-09-24 20:16 UTC, glorianaa80 reviewed
ya hice el code review

2019-09-24 20:16 UTC, glorianaa80 commented on src/scss/sections/header/_date.scss
> +  display: flex;
orden alfabético

2019-09-24 20:16 UTC, glorianaa80 commented on src/scss/sections/works/_works.scss
> +	}
identación

2019-09-24 20:16 UTC, glorianaa80 commented on src/scss/settings/_keyframes.scss
> +  0%{
espacio después de los  braquets

2019-09-25 01:15 UTC, jleiva requested changes

2019-09-25 01:15 UTC, jleiva commented on public/index.html
> +        <source src="./mp4/10 Most Disturbing Pieces Of Art Ever Made.mp4" type="video/mp4">
los nombres de los files que no tengan espacio ni caracteres especiales, esto pueda dar problemas.

Cual es el fallback? que pasa si el browser no soporta mp4?

2019-09-25 01:15 UTC, jleiva commented on public/index.html
> +      <a class="wrapper-social__icon insta" href="#"></a>
porque estos links no tienen href? a donde van a linquear?

2019-09-25 01:15 UTC, jleiva commented on src/js/nav.js
> +  function openNav() {
todo esto se puede cubrir a puro CSS, y que desde javascript solo se revise por una clase. Por ejemplo, si al darle click al boton el elemento no tiene la clase is-open, entonces se le pone, y si ya la tiene se le quita, un toggle.

Ojo esto https://github.com/cetav-ddw/cegea/blob/develop/src/js/menu.js

2019-09-25 01:15 UTC, jleiva commented on src/scss/components/_copy.scss
> +  //font-family: $proxy-txt;
si no se necesita, borrarlo

2019-09-25 01:15 UTC, jleiva commented on src/scss/layout/_grid.scss
> +.header {
revisa la indentacion del file

2019-09-25 01:15 UTC, jleiva commented on src/scss/sections/header/_nav.scss
> +  content: "menú";
cual es la razon por la que usas content, y no incluir el texto en el boton?

2019-09-25 01:15 UTC, jleiva commented on src/scss/sections/modalities/_social.scss
> +  grid-template-areas: "insta face"
negativo el uso de grids, el soporte no esta todavia en un punto estable

2019-09-25 02:44 UTC, JgeovanniAm commented on public/index.html
> +        <source src="./mp4/10 Most Disturbing Pieces Of Art Ever Made.mp4" type="video/mp4">
gracias... no había pensado en eso.

2019-09-25 02:45 UTC, JgeovanniAm commented on public/index.html
> +      <a class="wrapper-social__icon insta" href="#"></a>
hasta que se definan los nombres de los .html se ponen los href... aun no están en el proyecto

2019-09-25 02:50 UTC, JgeovanniAm commented on src/scss/sections/header/_nav.scss
> +  content: "menú";
pensé que era mejor opción que tratar de acomodar el propio texto del btn, y pensé que iba ser mas complejo acomodar el texto de tal forma que me quede igual que el diseño

2019-09-25 02:52 UTC, JgeovanniAm commented on src/scss/sections/modalities/_social.scss
> +  grid-template-areas: "insta face"
usé grid ahí por que no quería hacer tanto "wrappers y poderlo acomodar" para algo tan pequeño, pero voy hacer el cambio

2019-09-25 05:05 UTC, jleiva commented on public/index.html
> +      <a class="wrapper-social__icon insta" href="#"></a>
ok

2019-09-25 06:12 UTC, JgeovanniAm commented on public/index.html
> +        <source src="./mp4/10 Most Disturbing Pieces Of Art Ever Made.mp4" type="video/mp4">
leiva por el momento solo he puesto el "poster" porqué no hay otro formato de video por el momento. 
Además esos mp4 que vio en el proyecto, son de prueba osea , que no es el que está haciendo nuestro colega de post-producción

2019-09-26 05:13 UTC, jleiva requested changes

2019-09-26 05:13 UTC, jleiva commented on public/index.html
> +      <img class="animation-image__image" src="./img/header.png" alt="proxy logo">
hablamos sobre usar texto y hacer reemplazo del texto con un SVG

2019-09-26 05:13 UTC, jleiva commented on public/index.html
> +        <source src="./mp4/main.mp4" type="video/mp4">
no recuerdo este toque, pero si el browser no soporta el formato del video, la imagen del atributo poster queda como un fallback?

2019-09-26 05:13 UTC, jleiva commented on src/scss/layout/_grid.scss
> +		padding: 30px 0 120px 0;
esto se puede cambiar a 30px 0 120px;

Revisa la identacion del archivo, porfa

2019-09-26 05:13 UTC, jleiva commented on src/scss/sections/header/_nav.scss
> +  content: "menú";
como ya hablamos, usar el elemento button, incluir el texto de Menu y usar un icono

2019-09-26 05:13 UTC, jleiva commented on src/scss/sections/modalities/_social.scss
> +}
una linea nueva entre bloque de reglas no anidadas

2019-09-26 05:13 UTC, jleiva commented on src/scss/sections/works/_works.scss
> +  margin: 30px 0 80px 0;
margin se puede cambiar a 30px 0 80px;

2019-09-26 05:13 UTC, jleiva commented on src/scss/sections/works/_works.scss
> +  content: "David gonzales ramirez";
siempre va a tener el mismo nombre?

2019-09-26 05:24 UTC, JgeovanniAm commented on src/scss/sections/works/_works.scss
> +  content: "David gonzales ramirez";
Tengo pensado con js meter esos datos y modificar el content con js

2019-09-27 23:21 UTC, jleiva requested changes

2019-09-27 23:21 UTC, jleiva commented on public/index.html
> +      <h1 class="wrapper-animation__item">replace-image</h1>
Solo ponemos tener un h1

2019-10-02 15:55 UTC, merged